#!/usr/bin/env bash
# proxy-config-utility — guided installer.
#
# Interactive: asks for your proxy settings, then installs the detector + helper,
# wires up your shell(s), optionally sets up automatic detection (macOS launchd /
# Linux systemd timer), optional SSH routing, and an optional git-proxy hook.
#
# Safe to re-run (idempotent); backs up any file it changes. Run it from the repo:
#     ./install.sh
set -u

REPO="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
OS="$(uname -s)"
CFG_DIR="$HOME/.config/proxy-config"
CFG="$CFG_DIR/config"
BIN="$HOME/bin"

say(){ printf '%s\n' "$*" >&2; }
hr(){  printf -- '------------------------------------------------------------\n' >&2; }
ask(){ # ask "prompt" "default" -> echoes the answer (prompt goes to stderr)
  local p="$1" d="${2:-}" in
  if [ -n "$d" ]; then printf '%s [%s]: ' "$p" "$d" >&2; else printf '%s: ' "$p" >&2; fi
  IFS= read -r in || true
  printf '%s' "${in:-$d}"
}
yesno(){ # yesno "prompt" "y|n" -> return 0 for yes
  local in; in="$(ask "$1" "$2")"
  case "$(printf '%s' "$in" | tr 'A-Z' 'a-z')" in y|yes) return 0;; *) return 1;; esac
}
backup(){ [ -e "$1" ] && cp "$1" "$1.bak.$(date +%Y%m%d%H%M%S)" && say "  backed up $1"; }
ensure_line(){ # ensure_line FILE LINE  (append once)
  local f="$1" line="$2"
  [ -e "$f" ] || : > "$f"
  if grep -qF -- "$line" "$f" 2>/dev/null; then say "  = already wired: $(basename "$f")"
  else printf '\n# proxy-config-utility\n%s\n' "$line" >> "$f"; say "  + wired $(basename "$f")"; fi
}

say "== proxy-config-utility installer =="
say "repo: $REPO    os: $OS"
hr

# 1) scripts on PATH (symlinked to the repo so 'git pull' keeps them current)
mkdir -p "$BIN"
ln -sf "$REPO/bin/proxy-detect"    "$BIN/proxy-detect"
ln -sf "$REPO/bin/proxy-reachable" "$BIN/proxy-reachable"
say "installed $BIN/proxy-detect and $BIN/proxy-reachable"
case ":$PATH:" in *":$BIN:"*) :;; *) say "note: $BIN isn't on PATH — fine, the integration uses absolute paths";; esac
hr

# 2) interview
say "Proxy settings (press Enter to accept the [default]):"
PROBE_HOST="$(ask "  Probe host (reachable ONLY when behind the proxy)" "proxy.example.com")"
PROBE_PORT="$(ask "  Probe port" "8080")"
HTTP_URL="$(ask  "  HTTP proxy URL" "http://$PROBE_HOST:$PROBE_PORT")"
HTTPS_URL="$(ask "  HTTPS proxy URL" "$HTTP_URL")"
SOCKS_URL="$(ask "  SOCKS5 proxy URL (blank to skip)" "socks5://$PROBE_HOST:1080")"
NOPROXY="$(ask   "  no_proxy list" "127.0.0.1,localhost,.example.com,.internal,.local,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16")"
COLOR_ON="$(ask  "  Prompt color BEHIND proxy (256-color SGR)" "38;5;33")"
COLOR_OFF="$(ask "  Prompt color when DIRECT (256-color SGR)" "38;5;51")"
hr

# 3) write config
mkdir -p "$CFG_DIR"
WRITE_CFG=1
if [ -e "$CFG" ]; then yesno "Config $CFG exists — overwrite?" "n" && backup "$CFG" || WRITE_CFG=0; fi
if [ "$WRITE_CFG" = 1 ]; then
  cat > "$CFG" <<EOF
# proxy-config-utility — generated by install.sh $(date -u +%Y-%m-%dT%H:%M:%SZ)
PROXY_PROBE_HOST="$PROBE_HOST"
PROXY_PROBE_PORT="$PROBE_PORT"
HTTP_PROXY_URL="$HTTP_URL"
HTTPS_PROXY_URL="$HTTPS_URL"
SOCKS_PROXY_URL="$SOCKS_URL"
NO_PROXY_LIST="$NOPROXY"
PROXY_COLOR_ON="$COLOR_ON"
PROXY_COLOR_OFF="$COLOR_OFF"
EOF
  say "wrote $CFG"
else say "kept existing $CFG"; fi
hr

# 4) shell integration
say "Shell integration:"
yesno "  Wire up bash (~/.bashrc)?" "$( [ -e "$HOME/.bashrc" ] && echo y || echo n )" && ensure_line "$HOME/.bashrc" "source \"$REPO/shell/bash.sh\""
yesno "  Wire up zsh (~/.zshrc)?"   "$( [ -e "$HOME/.zshrc" ]  && echo y || echo n )" && ensure_line "$HOME/.zshrc"  "source \"$REPO/shell/zsh.sh\""
if command -v fish >/dev/null 2>&1; then
  yesno "  Wire up fish (conf.d)?" "y" && { mkdir -p "$HOME/.config/fish/conf.d"; ln -sf "$REPO/shell/proxy.fish" "$HOME/.config/fish/conf.d/proxy.fish"; say "  + linked fish conf.d/proxy.fish"; }
fi
[ "$OS" = Darwin ] && [ -e "$HOME/.bash_profile" ] && say "note: macOS bash login shells read ~/.bash_profile — make sure it sources ~/.bashrc."
hr

# 5) automatic detection
say "Automatic detection:"
if [ "$OS" = Darwin ]; then
  if yesno "  Install macOS launchd agent (login + every 5 min + on net change)?" "y"; then
    PLIST="$HOME/Library/LaunchAgents/local.proxy-detect.plist"
    mkdir -p "$HOME/Library/LaunchAgents" "$HOME/.cache/proxy"
    sed -e "s#/ABSOLUTE/PATH/TO/bin/proxy-detect#$BIN/proxy-detect#" \
        -e "s#/ABSOLUTE/PATH/TO/.cache/proxy/launchd.log#$HOME/.cache/proxy/launchd.log#g" \
        "$REPO/macos/local.proxy-detect.plist" > "$PLIST"
    launchctl bootout "gui/$(id -u)" "$PLIST" 2>/dev/null || true
    launchctl bootstrap "gui/$(id -u)" "$PLIST" 2>/dev/null && launchctl kickstart -k "gui/$(id -u)/local.proxy-detect" 2>/dev/null && say "  + launchd agent loaded" || say "  ! launchd load failed — load it manually (see macos/ comments)"
  fi
elif command -v systemctl >/dev/null 2>&1 && systemctl --user list-units >/dev/null 2>&1; then
  if yesno "  Install systemd --user timer (every 5 min)?" "y"; then
    mkdir -p "$HOME/.config/systemd/user"
    cp "$REPO/linux/proxy-detect.service" "$REPO/linux/proxy-detect.timer" "$HOME/.config/systemd/user/"
    systemctl --user daemon-reload
    systemctl --user enable --now proxy-detect.timer 2>/dev/null && say "  + systemd timer enabled" || say "  ! timer enable failed"
  fi
else
  say "  no user scheduler available — manual mode (run 'proxy-refresh' after network changes)"
fi
hr

# 6) SSH routing
if yesno "Set up SSH routing (SOCKS only when behind proxy AND host not directly reachable)?" "n"; then
  DEF_SOCKS="${SOCKS_URL#socks5://}"; DEF_SOCKS="${DEF_SOCKS:-$PROBE_HOST:1080}"
  SSH_SOCKS="$(ask "  SOCKS host:port for ssh ProxyCommand" "$DEF_SOCKS")"
  mkdir -p "$HOME/.ssh"; chmod 700 "$HOME/.ssh" 2>/dev/null || true
  if grep -q 'proxy-reachable' "$HOME/.ssh/config" 2>/dev/null; then say "  = ~/.ssh/config already has the proxy Match"
  else
    backup "$HOME/.ssh/config"; tmp="$(mktemp)"
    cat > "$tmp" <<EOF
# proxy-config-utility: SOCKS only when behind the proxy AND target not directly reachable.
Match exec "grep -q '^PROXY_STATUS=proxy_yes' ~/.cache/proxy/state.env && ! ~/bin/proxy-reachable %h %p"
    ProxyCommand nc -X 5 -x $SSH_SOCKS %h %p

EOF
    [ -e "$HOME/.ssh/config" ] && cat "$HOME/.ssh/config" >> "$tmp"
    mv "$tmp" "$HOME/.ssh/config"; chmod 600 "$HOME/.ssh/config"
    say "  + prepended SSH Match (SOCKS $SSH_SOCKS)"
  fi
fi
hr

# 7) git-proxy on-change hook
if yesno "Install on-change hook to set git's http/https proxy automatically?" "n"; then
  HOOK="$CFG_DIR/on-change"
  sed "s#http://proxy.effndc.com:8080#$HTTP_URL#g" "$REPO/config/on-change.example" > "$HOOK"
  chmod +x "$HOOK"; say "  + installed $HOOK (git proxy -> $HTTP_URL)"
fi
hr

# 8) prime + verify
say "Priming detection..."
"$BIN/proxy-detect" && say "  ran proxy-detect"
say "Current state:"; sed 's/^/  /' "$HOME/.cache/proxy/state.env" 2>/dev/null
hr
say "Done. Open a NEW shell (or re-source your rc) for the colored prompt."
say "Commands: 'proxy-refresh' (re-detect now), 'proxy-sync' (adopt cached state)."
